# https://pages-themes.github.io/cayman/
theme: jekyll-theme-cayman
title: Shepton Tech Meetup
description: A monthly pow-wow for like-minded tech folk in Shepton Mallet, UK
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
